DROP TABLE IF EXISTS Projects;
DROP TABLE IF EXISTS Releases;

CREATE TABLE Projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE Releases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  major INTEGER NOT NULL,
  minor INTEGER NOT NULL,
  FOREIGN KEY (project_id) REFERENCES Projects (id)
);
